spring:
  application:
    name: spring-templete
  jpa:
    show-sql: false
    generate-ddl: true
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        format_sql: false
        use_sql_comments: true
        default_batch_fetch_size: 1000
        dialect: org.hibernate.dialect.MySQLDialect
    database: mysql
  profiles:
    include:
      - database
      - swagger
